services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api/.env

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    env_file:
      - ./api/.env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: