site_name: Docs - Sua Grade UnB
repo_url: https://github.com/unb-mds/2023-2-Squad11

nav:
  - Home: index.md
  - Como contribuir?: contributing.md
  - Sprints:
    - Sprint 0: sprints/sprint-0.md
    - Sprint 1: sprints/sprint-1.md
    - Sprint 2: sprints/sprint-2.md
    - Sprint 3: sprints/sprint-3.md
    - Sprint 4: sprints/sprint-4.md
    - Sprint 5: sprints/sprint-5.md
    - Sprint 6: sprints/sprint-6.md

  - Frontend:
    - Sprint 0: frontend/sprint-0.md 
    - Sprint 1: frontend/sprint-1.md
    - Sprint 2: frontend/sprint-2.md
    - Sprint 3: frontend/sprint-3.md
    - Sprint 4: frontend/sprint-4.md 
    - Sprint 5: frontend/sprint-5.md
    - Sprint 6: frontend/sprint-6.md

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky

  palette:
    primary: "indigo"

  icon:
    repo: fontawesome/brands/github
